/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner */

#ifndef _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
#define _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_init
  (JNIEnv *, jclass);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_create
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    setConfig
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_setConfig
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    parseConfig
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_parseConfig
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    enableCache
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_enableCache
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    getResults
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_getResults
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner
 * Method:    scanImage
 * Signature: (Lcom/stynet/shuidianbing/opticalcharacterrecognition/zbar/Image;)I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_ImageScanner_scanImage
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
