/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image */

#ifndef _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
#define _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_init
  (JNIEnv *, jclass);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_create
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    convert
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_convert
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setFormat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getSequence
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getSequence
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setSequence
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setSequence
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getSize
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getSize
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setSize__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setSize
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setSize___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getCrop
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getCrop
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setCrop
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setCrop__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setCrop
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setCrop___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setData___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    setData
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_setData___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image
 * Method:    getSymbols
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Image_getSymbols
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
