/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol */

#ifndef _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
#define _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
#ifdef __cplusplus
extern "C" {
#endif
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_NONE
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_NONE 0L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_PARTIAL
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_PARTIAL 1L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_EAN8
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_EAN8 8L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_UPCE
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_UPCE 9L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_ISBN10
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_ISBN10 10L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_UPCA
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_UPCA 12L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_EAN13
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_EAN13 13L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_ISBN13
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_ISBN13 14L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_I25
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_I25 25L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_DATABAR
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_DATABAR 34L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_DATABAR_EXP
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_DATABAR_EXP 35L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODABAR
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODABAR 38L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODE39
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODE39 39L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_PDF417
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_PDF417 57L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_QRCODE
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_QRCODE 64L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODE93
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODE93 93L
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODE128
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_CODE128 128L
/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_init
  (JNIEnv *, jclass);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getConfigMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getConfigMask
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getModifierMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getModifierMask
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getDataBytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getDataBytes
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getQuality
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getQuality
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getLocationSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getLocationSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getLocationX
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getLocationX
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getLocationY
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getLocationY
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getOrientation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getOrientation
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    getComponents
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_getComponents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol
 * Method:    next
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_Symbol_next
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
