/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet */

#ifndef _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet
#define _Included_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet
#ifdef __cplusplus
extern "C" {
#endif
#undef com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet_MAX_ARRAY_SIZE
#define com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet_MAX_ARRAY_SIZE 2147483639L
/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet_init
  (JNIEnv *, jclass);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet_size
  (JNIEnv *, jobject);

/*
 * Class:     com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet
 * Method:    firstSymbol
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_stynet_shuidianbing_opticalcharacterrecognition_zbar_SymbolSet_firstSymbol
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
